// =====================================================================
// Base de conhecimento do Lis PDV (Central de Ajuda, botão F1, apostila)
// ---------------------------------------------------------------------
// Escrita por pessoas, sem IA. Cada artigo:
//   id, cat, titulo, niveis (quem vê), rota (tela que o botão "Ir para a tela" abre),
//   termos (como um leigo pergunta: sinônimos, erros comuns de escrita),
//   resumo, passos[], dicas[], atencao[], ver[] (artigos relacionados)
// Para ensinar algo novo ao sistema: copie um artigo parecido e ajuste.
// Os problemas técnicos do Diagnóstico (diagnostico/catalogo.js) entram sozinhos.
// =====================================================================

const T = ["admin", "gerente", "caixa", "atendente", "cozinha"];   // todos
const AG = ["admin", "gerente"];
const AGC = ["admin", "gerente", "caixa"];
const AGCT = ["admin", "gerente", "caixa", "atendente"];
const A = ["admin"];

export const CATEGORIAS = [
  ["comecar", "Primeiros passos", "entrar"],
  ["vender", "Vender e receber", "pdv"],
  ["caixa", "Caixa e dinheiro", "caixa"],
  ["restaurante", "Mesas, garçom e cozinha", "mesa"],
  ["delivery", "Delivery e cardápio", "moto"],
  ["produtos", "Produtos, estoque e compras", "produtos"],
  ["clientes", "Clientes e fiado", "clientes"],
  ["gestao", "Gestão e relatórios", "relatorios"],
  ["config", "Configurações e equipamentos", "config"],
  ["equipe", "Equipe, acessos e segurança", "usuarios"],
  ["dados", "Backup, assinatura e dados", "pacote"],
  ["problemas", "Problemas e mensagens de erro", "alerta"],
  ["glossario", "O que significa", "caderno"],
  ["plataforma", "Superusuário e suporte", "coroa"],
];

export const ARTIGOS = [
  // ================================================================ PRIMEIROS PASSOS
  { id: "acessar-sistema", cat: "comecar", titulo: "Como entrar e sair do sistema", niveis: T,
    termos: "login entrar logar acessar senha email sair deslogar trocar operador endereco site link",
    resumo: "Cada pessoa entra com o próprio e-mail e senha. Tudo o que é feito fica registrado no nome de quem está conectado.",
    passos: ["Abra o Chrome ou o Edge e digite hfa90.github.io/pdv-web/app (salve nos favoritos).",
      "Digite seu e-mail e sua senha e clique em Entrar.",
      "Para sair, clique em Sair, no rodapé do menu lateral. Faça isso sempre que trocar de operador no caixa."],
    dicas: ["Garçom pode entrar no app do garçom só com matrícula (ou CPF) e senha de números.", "Crie um atalho na área de trabalho do caixa para abrir com um clique."],
    atencao: ["Nunca empreste o seu login: as vendas, descontos e cancelamentos ficam no seu nome."],
    ver: ["esqueci-senha", "niveis-acesso"] },
  { id: "esqueci-senha", cat: "comecar", titulo: "Esqueci a minha senha", niveis: T, rota: null,
    termos: "esqueci senha perdi senha nao lembro senha recuperar senha redefinir senha trocar senha senha errada nova senha",
    resumo: "Você mesmo pode criar uma senha nova pelo e-mail, ou o administrador/gerente define uma nova para você.",
    passos: ["Na tela de entrada, clique em Esqueci a senha.", "Digite o seu e-mail e abra o link que chegar (procure também no spam).", "Crie a senha nova (mínimo 8 caracteres) e entre de novo."],
    dicas: ["Funcionário sem acesso ao e-mail: peça ao administrador ou gerente para definir uma senha nova em Usuários.", "Garçom com matrícula: o gerente troca a senha numérica em Usuários."],
    ver: ["acessar-sistema", "tela-usuarios"] },
  { id: "niveis-acesso", cat: "comecar", titulo: "Níveis de acesso: quem pode fazer o quê", niveis: T, rota: "usuarios",
    termos: "nivel acesso permissao papel cargo funcao administrador gerente caixa garcom atendente cozinha quem pode porque nao aparece menu",
    resumo: "Cada login tem um nível. O menu mostra só o que a pessoa pode usar, e o servidor bloqueia o resto.",
    passos: ["Administrador: tudo, inclusive usuários, dados da empresa, nota fiscal e assinatura.",
      "Gerente: produtos, compras, estoque, financeiro, alertas, relatórios e cancelamentos; cria caixas, garçons e cozinha.",
      "Caixa: vende, recebe, abre e fecha o próprio caixa, recebe fiado e registra perdas.",
      "Atendente / garçom: lança pedidos, mesas e comandas; não recebe pagamento no caixa.",
      "Cozinha: vê só a tela da cozinha."],
    dicas: ["Dê a cada pessoa o menor nível que resolve o trabalho dela.", "Tenha pelo menos dois administradores (o dono e um sócio) para não ficar sem acesso."],
    ver: ["tela-usuarios", "erro-sem-permissao"] },
  { id: "implantacao", cat: "comecar", titulo: "Deixar a loja pronta: lista de implantação", niveis: AG, rota: "configuracoes",
    termos: "comecar implantar configurar loja primeira vez inicio passo a passo checklist preparar sistema novo cliente",
    resumo: "Siga esta ordem para a loja ficar pronta para vender.",
    passos: ["Configurações › Loja: endereço, CNPJ, fuso horário e mensagem do cupom.",
      "Configurações › PIX: a chave PIX da loja.",
      "Configurações › Impressora: configure e imprima um teste.",
      "Se vende por quilo: Configurações › Balança.",
      "Produtos: revise as categorias e cadastre ou importe os produtos com preço, custo e código de barras.",
      "Compras: lance o estoque inicial pelo XML das notas dos fornecedores.",
      "Financeiro › Taxas: as taxas da maquininha.",
      "Usuários: um login para cada funcionário.",
      "Configurações › Loja: o desconto máximo permitido aos caixas.",
      "Restaurante: monte o salão em Mesas e instale o app do garçom. Delivery: publique o cardápio.",
      "Alertas › Resumo do dia: ligue o e-mail diário.",
      "Se for emitir nota: Configurações › Nota fiscal (teste em homologação primeiro).",
      "Faça uma venda de teste completa: abrir caixa, vender, imprimir e fechar o caixa."],
    ver: ["config-loja", "config-pix", "config-impressora", "produto-cadastrar"] },
  { id: "conhecendo-tela", cat: "comecar", titulo: "Conhecendo a tela: menu, tema escuro e celular", niveis: T,
    termos: "menu lateral tela escura tema escuro modo noturno celular tablet menu sumiu esconder menu recolher fixar menu icone tres riscos",
    resumo: "Menu à esquerda, conteúdo à direita. O menu pode ficar fixo ou só com ícones.",
    passos: ["O botão no topo do menu alterna entre menu fixo e menu recolhível (só ícones, abre ao passar o mouse).",
      "No rodapé do menu: tema escuro, Ajuda desta tela, Pedir ajuda, seu nome/nível e Sair.",
      "No celular, o menu fica escondido: toque no ícone ☰ no topo para abrir."],
    dicas: ["Aperte F1 em qualquer tela para ver a ajuda daquela tela.", "O tema escuro cansa menos a vista à noite."] },
  { id: "rotina-dia", cat: "comecar", titulo: "A rotina de um dia na loja", niveis: T,
    termos: "rotina dia a dia abertura fechamento o que fazer manha tarde noite fim do dia fim do mes",
    resumo: "Um exemplo de dia, da abertura ao fechamento. Adapte à sua loja.",
    passos: ["Antes de abrir (gerente): confere o resumo de ontem e os alertas, lança as notas que chegaram e baixa o que venceu.",
      "Abertura (caixas): cada um entra com o próprio login e abre o caixa com o troco contado.",
      "Durante o dia: vendas pelo leitor, favoritos e balança; PIX com QR na tela; promoções entram sozinhas.",
      "Meio-dia (gerente): sangria do excesso de dinheiro, pedido de compra pelo WhatsApp e cobrança do fiado vencido.",
      "Se a internet cair: continue vendendo; as vendas são enviadas quando voltar.",
      "Troca de turno: resumo parcial, fechamento com a contagem e Sair.",
      "Fim do dia: registrar sobras como perda e cada um fechar o seu caixa.",
      "Fim do mês (dono): lucro real, contas do próximo mês, curva ABC e exportar relatórios para o contador."] },

  // ================================================================ VENDER
  { id: "tela-vender", cat: "vender", titulo: "Tela Vender (PDV): como vender", niveis: AGCT, rota: "pdv",
    termos: "vender venda pdv frente de caixa lancar produto passar produto registrar venda cupom como vender comecar venda",
    resumo: "A tela onde as vendas acontecem: funciona com toque, mouse, teclado, leitor de código de barras e balança.",
    passos: ["Adicione os produtos: toque no botão do produto, digite parte do nome na busca (F2) ou passe no leitor.",
      "Para mudar a quantidade, selecione o item e use − e + (ou F4).",
      "Se precisar: desconto (F6), CPF/cliente (botão CPF) ou mesa/comanda (botão Mesa).",
      "Clique em Receber (F9) para cobrar.",
      "Escolha a forma de pagamento, confira o troco e clique em Concluir venda."],
    dicas: ["Busca ignora acentos: “pao” acha “Pão francês”.", "Vários de uma vez: 6*7894900011517 adiciona 6 unidades.", "Produtos sem estoque aparecem mais claros, mas podem ser vendidos."],
    atencao: ["Para receber, o caixa precisa estar aberto (aparece um aviso amarelo com o botão Abrir caixa)."],
    ver: ["receber-pagamento", "atalhos-teclado", "produto-peso", "desconto", "abrir-caixa"] },
  { id: "atalhos-teclado", cat: "vender", titulo: "Atalhos de teclado do PDV", niveis: AGCT, rota: "pdv",
    termos: "atalho teclado tecla f2 f4 f6 f8 f9 f10 esc delete enter rapido agilizar",
    resumo: "Teclas para vender sem tirar a mão do teclado.",
    passos: ["F2: vai para a busca de produtos.", "F4: altera a quantidade do item selecionado.", "F6: desconto, acréscimo e taxa de serviço.",
      "F8: salva o pedido (mesa ou comanda).", "F9 ou F10: abre o recebimento.", "↑ ↓: seleciona o item anterior ou o próximo.",
      "Delete: remove o item selecionado.", "Esc: limpa o cupom (pede confirmação) ou fecha a janela aberta.",
      "No pagamento: Alt+1 Dinheiro, Alt+2 PIX, Alt+3 Débito, Alt+4 Crédito, Alt+5 Vale, Alt+6 Crediário.",
      "3*código: adiciona 3 unidades do produto.", "F1: ajuda da tela em que você está."] },
  { id: "produto-peso", cat: "vender", titulo: "Vender produto por peso (quilo) e etiqueta da balança", niveis: AGC, rota: "pdv",
    termos: "peso quilo kg grama balanca pesar vender por quilo granel etiqueta da balanca codigo 2 frios",
    resumo: "Produtos com unidade KG, G, L, ML ou M pedem a quantidade ou leem a balança.",
    passos: ["Toque no produto vendido por peso.", "Sem balança: digite com vírgula, por exemplo 0,350 para 350 gramas.",
      "Com balança configurada: coloque no prato; o item entra sozinho quando o peso estabiliza (ou use Digitar peso).",
      "Etiqueta impressa pela balança (código de 13 dígitos começando com 2): passe no leitor; o sistema acha o produto e calcula o peso."],
    atencao: ["O código interno do produto precisa ser o mesmo cadastrado na balança."],
    ver: ["config-balanca", "erro-balanca"] },
  { id: "item-alterar", cat: "vender", titulo: "Alterar, anotar ou tirar um item do cupom", niveis: AGCT, rota: "pdv",
    termos: "tirar item remover item apagar item errado quantidade errada observacao sem cebola anotar item limpar cupom desfazer item",
    resumo: "Selecione o item no cupom e use os controles que aparecem.",
    passos: ["Clique no item (ou use ↑ ↓).", "Quantidade: − e +, digite no campo do meio ou F4.", "Observação: “sem cebola”, “para viagem” — sai no pedido e na cozinha.",
      "Remover: ícone da lixeira ou tecla Delete.", "Limpar tudo: Esc (pede confirmação)."],
    atencao: ["Tirar um item de mesa/comanda lançado há mais de 5 minutos exige gerente e fica registrado."] },
  { id: "receber-pagamento", cat: "vender", titulo: "Receber o pagamento (dinheiro, PIX, cartão, dividido)", niveis: AGC, rota: "pdv",
    termos: "receber pagar pagamento cobrar troco dinheiro cartao debito credito vale refeicao dividir pagamento duas formas metade pix",
    resumo: "Uma ou várias formas na mesma venda; o sistema calcula o troco.",
    passos: ["Clique em Receber (F9).", "Escolha a forma (Alt+1 a 6). O campo já vem com o valor que falta.",
      "Para pagar tudo numa forma, aperte Enter para lançar e Enter de novo para concluir.",
      "No dinheiro, use os botões de nota (R$ 50, R$ 100…) para o troco.",
      "Para dividir: informe um valor menor, troque a forma e informe o restante.",
      "Confira Pago, Falta e Troco e clique em Concluir venda."],
    dicas: ["Lançou errado? Clique no ✕ da linha do pagamento.", "O que já foi pago fica guardado na venda, mesmo se a energia cair."],
    atencao: ["Troco só no dinheiro: cartão e PIX não podem passar do valor que falta."],
    ver: ["pix-qrcode", "venda-fiado", "erro-troco"] },
  { id: "pix-qrcode", cat: "vender", titulo: "Receber por PIX com QR Code", niveis: AGC, rota: "pdv",
    termos: "pix qr code qrcode copia e cola chave pix pagar pix cliente pagou pix confirmar pix codigo pix",
    resumo: "O QR Code sai com o valor exato e o dinheiro cai direto na conta da loja.",
    passos: ["No pagamento, escolha PIX.", "Mostre o QR ao cliente (ou toque em Copiar código e mande pelo WhatsApp).",
      "Confira o crédito no app do banco.", "Clique em PIX recebido."],
    dicas: ["Imprimir QR tira o QR na térmica (balcão ou entrega).", "Com Mercado Pago ligado em Configurações › PIX, o sistema confirma sozinho."],
    atencao: ["Só clique em PIX recebido depois de ver o dinheiro no banco: comprovante na tela do cliente pode ser falso."],
    ver: ["config-pix", "erro-pix-banco", "conferencia-pix"] },
  { id: "desconto", cat: "vender", titulo: "Dar desconto, acréscimo ou taxa de serviço", niveis: AGCT, rota: "pdv",
    termos: "desconto abatimento acrescimo taxa de servico dez por cento 10% gorjeta diminuir preco",
    resumo: "F6 abre a janela de desconto, acréscimo e taxa de serviço.",
    passos: ["Clique em Desconto ou aperte F6.", "Digite o valor e escolha R$ ou %.", "Restaurante: use Taxa de serviço 10%.", "Clique em Aplicar."],
    atencao: ["Caixas e atendentes só dão desconto até o limite da loja (padrão 10%). Acima disso, só gerente."],
    ver: ["erro-desconto", "config-loja"] },
  { id: "cpf-nota", cat: "vender", titulo: "CPF na nota e escolher o cliente da venda", niveis: AGCT, rota: "pdv",
    termos: "cpf na nota cpf cnpj cliente na venda identificar cliente nota paulista",
    resumo: "Botão CPF no topo do cupom.",
    passos: ["Clique em CPF no topo do cupom.", "Digite o CPF ou CNPJ (o sistema confere se é válido) ou busque um cliente cadastrado por nome ou telefone."],
    dicas: ["Para NF-e e fiado é preciso escolher um cliente cadastrado."] },
  { id: "mesa-comanda-pdv", cat: "vender", titulo: "Salvar pedido em mesa ou comanda (pagar depois)", niveis: AGCT, rota: "pdv",
    termos: "comanda mesa pedido aberto salvar pedido pagar depois conta aberta senha nome do cliente f8 pedidos",
    resumo: "Lance aos poucos e receba no final.",
    passos: ["Lance os itens.", "Clique em Mesa e digite a mesa, comanda, senha ou nome.", "Clique em Salvar pedido (F8).",
      "Para acrescentar ou fechar: clique em Pedidos e escolha a mesa.", "Adicione e salve de novo, ou clique em Receber para fechar."],
    dicas: ["Atendentes usam Enviar pedido: eles lançam e o caixa recebe."], ver: ["tela-mesas"] },
  { id: "gaveta", cat: "vender", titulo: "Abrir a gaveta de dinheiro", niveis: AGC, rota: "pdv",
    termos: "gaveta abrir gaveta gaveta nao abre dinheiro troco cofre",
    resumo: "O botão da gaveta, ao lado da busca, abre a gaveta ligada à impressora e registra quem abriu.",
    passos: ["Clique no ícone da gaveta.", "Escolha o motivo (troco, conferência…)."],
    atencao: ["A gaveta só abre sozinha com a impressora em USB/serial e a opção Abrir gaveta ao imprimir marcada.", "Gaveta aberta muitas vezes sem venda aparece nos alertas."],
    ver: ["config-impressora"] },
  { id: "promocao-no-cupom", cat: "vender", titulo: "Por que entrou um desconto sozinho? (promoções)", niveis: AGCT, rota: "pdv",
    termos: "desconto sozinho promocao automatica leve 3 pague 2 combo atacado preco diferente verde no cupom",
    resumo: "As promoções cadastradas entram sozinhas: o item mostra em verde o nome da promoção e o desconto.",
    passos: ["O caixa não precisa fazer nada; o servidor confere a mesma regra.", "Promoções não se somam: vale a que dá mais desconto em cada item."],
    ver: ["tela-promocoes"] },
  { id: "venda-outro-aparelho", cat: "vender", titulo: "Continuar a venda em outro computador ou celular", niveis: AGC, rota: "pdv",
    termos: "computador travou pc quebrou continuar venda outro aparelho celular tablet venda em andamento continuar aqui pane",
    resumo: "Se o computador do caixa der problema, continue a mesma venda em outro aparelho.",
    passos: ["No outro aparelho, entre com o mesmo usuário.", "Abra Vender: aparece Venda em andamento em outro aparelho (também em Pedidos).",
      "Clique em Continuar aqui. Itens e pagamentos vêm junto."],
    atencao: ["Sem internet, a venda em andamento só existe no aparelho antigo e volta quando ele for religado."],
    ver: ["sem-internet"] },

  // ================================================================ CAIXA
  { id: "tela-caixa", cat: "caixa", titulo: "Tela Caixa: abrir, sangria, suprimento e fechar", niveis: AGC, rota: "caixa",
    termos: "caixa tela caixa turno controle dinheiro gaveta operador",
    resumo: "Controla o dinheiro da gaveta de cada operador, do começo ao fim do turno. Cada pessoa tem o seu caixa.",
    passos: ["Abrir caixa: informe o troco que está na gaveta.", "Sangria: tirou dinheiro da gaveta (cofre, pagamento).", "Suprimento: colocou dinheiro (reforço de troco).",
      "Resumo parcial: imprime quanto vendeu sem fechar.", "Fechar caixa: conte o dinheiro e confirme."],
    ver: ["abrir-caixa", "sangria-suprimento", "fechar-caixa"] },
  { id: "abrir-caixa", cat: "caixa", titulo: "Abrir o caixa", niveis: AGC, rota: "caixa",
    termos: "abrir caixa iniciar caixa comecar turno fundo de troco caixa fechado nao consigo vender",
    resumo: "Antes de vender, cada operador abre o próprio caixa com o dinheiro do troco.",
    passos: ["Vá em Caixa e clique em Abrir caixa (ou use o aviso amarelo do PDV).", "Conte o dinheiro que já está na gaveta e informe como fundo de troco.",
      "Dê um nome ao terminal, como “Caixa 1”."],
    atencao: ["Abrir o caixa precisa de internet. Depois de aberto, ele vende mesmo se a internet cair."],
    ver: ["erro-caixa-fechado"] },
  { id: "sangria-suprimento", cat: "caixa", titulo: "Sangria e suprimento (tirar ou pôr dinheiro na gaveta)", niveis: AGC, rota: "caixa",
    termos: "sangria retirada tirar dinheiro cofre suprimento reforco por dinheiro troco colocar dinheiro",
    resumo: "Sangria é tirar dinheiro da gaveta; suprimento é colocar dinheiro que não é venda.",
    passos: ["Em Caixa, clique em Sangria ou Suprimento.", "Informe o valor e o motivo e confirme."],
    dicas: ["Fiado recebido em dinheiro entra sozinho como suprimento, com o nome do cliente."] },
  { id: "fechar-caixa", cat: "caixa", titulo: "Fechar o caixa e conferir a diferença", niveis: AGC, rota: "caixa",
    termos: "fechar caixa fechamento encerrar turno conferir caixa contar dinheiro diferenca falta sobra caixa nao fecha",
    resumo: "Conte o dinheiro da gaveta; o sistema compara com o esperado e mostra a diferença.",
    passos: ["Clique em Fechar caixa.", "Conte todo o dinheiro e informe em Dinheiro contado.", "Deixe Imprimir fechamento marcado.", "Confirme e assine o comprovante."],
    dicas: ["Dinheiro esperado = troco inicial + vendas em dinheiro (menos troco) + suprimentos − sangrias.",
      "Gerente: na lista de caixas, clique numa linha para ver, reimprimir ou fechar o caixa que alguém esqueceu aberto."],
    atencao: ["Se houver vendas feitas sem internet ainda não enviadas, o sistema envia antes de deixar fechar.", "Mesas e comandas não pagas não impedem o fechamento."] },

  // ================================================================ VENDAS
  { id: "tela-vendas", cat: "vender", titulo: "Tela Vendas: consultar, reimprimir e cancelar", niveis: AGC, rota: "vendas",
    termos: "vendas historico consultar venda achar venda reimprimir cupom segunda via numero da venda",
    resumo: "O histórico completo das vendas, com tudo o que aconteceu em cada uma.",
    passos: ["Escolha o período (De / Até), a situação ou digite o número da venda ou mesa.", "Clique na venda para ver itens, pagamentos e notas.",
      "No rodapé: Reimprimir, Emitir NFC-e/NF-e, DANFE/XML, Atualizar, Cancelar nota e Cancelar venda."],
    ver: ["cancelar-venda", "nota-fiscal-tipos"] },
  { id: "cancelar-venda", cat: "vender", titulo: "Cancelar uma venda", niveis: AG, rota: "vendas",
    termos: "cancelar venda estornar devolver dinheiro desfazer venda venda errada anular",
    resumo: "Só gerente ou administrador cancela venda finalizada, sempre com motivo.",
    passos: ["Em Vendas, abra a venda e clique em Cancelar venda.", "Escreva o motivo e confirme.", "Devolva o valor ao cliente pela mesma forma de pagamento."],
    dicas: ["Os itens voltam ao estoque e o fiado é estornado sozinho."],
    atencao: ["Com nota fiscal autorizada, cancele primeiro a nota (justificativa de 15+ letras). A NFC-e tem prazo curto, em geral 30 minutos."] },

  // ================================================================ RESTAURANTE
  { id: "tela-mesas", cat: "restaurante", titulo: "Tela Mesas: atender as mesas do salão", niveis: AGCT, rota: "mesas",
    termos: "mesa mesas salao mapa abrir mesa conta da mesa pedir conta mesa ocupada livre",
    resumo: "Mapa do salão ao vivo: livre (verde), ocupada (laranja) e conta pedida (vermelho).",
    passos: ["Toque na mesa livre e em Abrir mesa e lançar pedido.", "Lance os itens (com observação); eles vão para a cozinha.",
      "Pedir conta: a mesa fica vermelha e dá para imprimir a conferência com serviço e valor por pessoa.",
      "Transferir / juntar: muda de mesa, junta mesas ou passa só alguns itens.", "Receber no caixa: abre a mesa no PDV para fechar."],
    dicas: ["A barra de cor mostra há quanto tempo a mesa está ocupada.", "Comandas abertas também aparecem aqui."],
    ver: ["montar-salao", "app-garcom", "transferir-itens"] },
  { id: "montar-salao", cat: "restaurante", titulo: "Montar o salão (cadastrar as mesas)", niveis: AG, rota: "mesas",
    termos: "cadastrar mesa criar mesa montar salao desenho do salao area varanda numerar mesas",
    resumo: "Crie as mesas e arraste para ficar igual ao seu salão.",
    passos: ["Em Mesas, clique em Editar salão.", "Criar várias: cadastra de uma vez (ex.: 1 a 20 no Salão).", "Arraste as mesas; toque numa mesa para mudar nome, área, lugares e formato.", "Organizar em fileiras arruma tudo sozinho."] },
  { id: "transferir-itens", cat: "restaurante", titulo: "Transferir mesa, juntar contas ou passar itens", niveis: AGC, rota: "mesas",
    termos: "transferir mesa juntar mesa trocar de mesa passar item outra mesa dividir conta comanda nova",
    resumo: "Mude a mesa inteira de lugar, junte contas ou passe só alguns itens (até quantidade parcial).",
    passos: ["Abra a mesa e toque em Transferir.", "Escolha a mesa inteira ou só os itens e a quantidade.", "Escolha o destino: outra mesa, uma comanda aberta ou uma comanda nova."],
    dicas: ["Tudo fica no registro de atividades."] },
  { id: "app-garcom", cat: "restaurante", titulo: "Instalar e usar o app do garçom no celular", niveis: AGCT, rota: "mesas",
    termos: "app garcom aplicativo celular garcom instalar app tablet garcom matricula qr do garcom",
    resumo: "O garçom lança pedidos pelo celular e tudo aparece na hora no caixa e na cozinha.",
    passos: ["No sistema, em Mesas › App do garçom, mostre o QR Code ao garçom (ou copie o link).",
      "No celular, abra no Chrome (Android) ou Safari (iPhone) e toque em Instalar / Adicionar à tela de início.",
      "O garçom entra com a matrícula (ou CPF) e a senha de números.",
      "Ele vê o salão ao vivo, abre mesas, lança itens, pede a conta e acompanha a cozinha."],
    dicas: ["Se o sinal cair no salão, o app guarda o pedido e reenvia sozinho."],
    ver: ["garcom-login", "garcom-fechar-conta"] },
  { id: "garcom-login", cat: "restaurante", titulo: "Login do garçom por matrícula e senha de números", niveis: AG, rota: "usuarios",
    termos: "matricula garcom senha numerica pin garcom bloqueado garcom nao entra criar garcom",
    resumo: "Garçom pode ser criado sem e-mail: entra com matrícula ou CPF e uma senha só de números.",
    passos: ["Em Usuários, clique em Novo usuário e escolha Atendente / garçom.", "Preencha a matrícula (ou CPF) e uma senha de 6 a 12 números (sem 123456 ou 111111).",
      "O celular é ligado à loja uma vez pelo QR de Mesas › App do garçom."],
    atencao: ["5 senhas erradas bloqueiam por 15 minutos; o gerente libera em Usuários (abrindo o garçom e salvando)."] },
  { id: "tela-cozinha", cat: "restaurante", titulo: "Tela Cozinha: aprovar, preparar e marcar pronto", niveis: ["admin", "gerente", "caixa", "cozinha"], rota: "cozinha",
    termos: "cozinha pedido cozinha kds tela da cozinha preparar pronto servido fila pedido nao chegou na cozinha",
    resumo: "Os pedidos passam por: aguardando aprovação → na fila → preparando → pronto → servido.",
    passos: ["Pedidos do garçom podem precisar de aprovação do caixa/gerente (ou com a senha de aprovação).",
      "Na cozinha, toque em Preparar e depois em Pronto.", "O garçom é avisado no celular e marca Servido."],
    dicas: ["As cores mostram o tempo de preparo pela meta da loja.", "Use tela cheia e deixe o som ligado.", "Pedidos do delivery aceitos também entram aqui."],
    ver: ["senha-aprovacao", "config-restaurante"] },
  { id: "senha-aprovacao", cat: "restaurante", titulo: "Senha de aprovação dos pedidos do garçom", niveis: AGCT, rota: "cozinha",
    termos: "senha de aprovacao aprovar pedido aprovar com senha pedido aguardando aprovacao codigo 6 numeros",
    resumo: "Cada gerente e caixa tem uma senha de 6 números (troca sozinha a cada 7 dias) para aprovar pedidos no aparelho do garçom.",
    passos: ["No celular do garçom (ou na tela Cozinha), toque em Aprovar com senha.", "O caixa ou gerente digita a senha dele.",
      "Para ver a sua senha: botão Senha de aprovação no menu lateral (toque em Mostrar)."],
    dicas: ["Se alguém viu sua senha, gere outra na hora.", "O administrador vê e troca todas em Usuários › Senhas de aprovação.", "Dá para desligar a aprovação em Configurações › Restaurante."],
    atencao: ["5 senhas erradas em 15 minutos bloqueiam novas tentativas."] },
  { id: "tela-garcons", cat: "restaurante", titulo: "Garçons: desempenho, comissão e metas", niveis: ["admin", "gerente", "atendente"], rota: "garcons",
    termos: "garcons comissao meta desempenho ranking quanto vendi meu desempenho turno garcom ao vivo",
    resumo: "Vendido, mesas atendidas, ticket médio, comissão e projeção do mês. Para o garçom aparece como Meu desempenho.",
    passos: ["Escolha o período.", "Gerente: define meta e comissão por garçom e vê a aba Ao vivo.", "Garçom: vê o próprio desempenho e o turno (recebimentos e conferência com a maquininha)."],
    ver: ["config-restaurante"] },
  { id: "garcom-fechar-conta", cat: "restaurante", titulo: "Fechar a conta pelo app do garçom (PIX e cartão)", niveis: AGCT, rota: "mesas",
    termos: "fechar conta no app garcom recebe pix garcom maquininha cartao na mesa dividir conta por pessoa nsu",
    resumo: "O garçom cobra PIX ou cartão na mesa; tudo entra no caixa principal.",
    passos: ["Na mesa, toque em Fechar conta: aparece consumo, serviço, couvert e total.", "Divida se precisar (÷2, ÷3 ou por pessoa).",
      "PIX: mostre o QR. Cartão: passe na maquininha e confirme Aprovado (NSU opcional).", "Dinheiro: leve a conta ao caixa."],
    dicas: ["O caixa recebe aviso e vê a lista “Fechadas pelos garçons no app” na tela Caixa."] },
  { id: "config-restaurante", cat: "restaurante", titulo: "Taxa de serviço, couvert, comissão e cozinha", niveis: AG, rota: "configuracoes",
    termos: "taxa de servico couvert comissao garcom aprovacao cozinha tempo preparo caixa principal configurar restaurante",
    resumo: "Em Configurações › Restaurante o dono escolhe as regras do salão.",
    passos: ["Serviço: não cobrar, só sugerir ou cobrar, com o percentual.", "Couvert por pessoa, com nome próprio.", "Comissão sobre consumo ou sobre a taxa de serviço, e meta padrão.",
      "Aprovação da cozinha, metas de tempo e caixa principal (onde caem as contas fechadas no app)."] },

  // ================================================================ DELIVERY
  { id: "tela-delivery", cat: "delivery", titulo: "Tela Delivery: atender os pedidos do cardápio", niveis: AGC, rota: "delivery",
    termos: "delivery pedido online cardapio digital ifood entrega retirada aceitar pedido pedido novo som",
    resumo: "Pedidos chegam com aviso sonoro e passam por: novos → em preparo → pronto/a caminho → entregue.",
    passos: ["Pedido novo: confira e clique em Aceitar e imprimir (ou Recusar, com motivo).", "Pronto: clique em Pedido pronto; na entrega, Saiu para entrega.",
      "Ao entregar: Entregue · concluir e escolha como foi pago. A venda entra no caixa.", "PIX pago no cardápio já chega como pago."],
    dicas: ["O botão Recebendo pedidos abre e fecha a loja na hora (cozinha cheia)."], ver: ["publicar-cardapio"] },
  { id: "publicar-cardapio", cat: "delivery", titulo: "Publicar o cardápio digital", niveis: AG, rota: "configuracoes",
    termos: "cardapio digital publicar link do cardapio qr do cardapio foto produto cardapio taxa de entrega pedido minimo",
    resumo: "O cliente pede pelo link, paga por PIX ou na entrega e acompanha o pedido.",
    passos: ["Configurações › Delivery e cardápio: marque Receber pedidos e escolha o endereço (ex.: paobom).",
      "Informe taxa de entrega, pedido mínimo, tempo, entrega/retirada, horário e recado.",
      "Em Produtos, marque Mostrar no cardápio e coloque foto e descrição.", "Divulgue o link e o QR no WhatsApp, Instagram e nas mesas."] },

  // ================================================================ PRODUTOS
  { id: "tela-produtos", cat: "produtos", titulo: "Tela Produtos e categorias", niveis: AG, rota: "produtos",
    termos: "produtos cadastro de produtos lista de produtos categorias mercadoria item",
    resumo: "Cadastro de produtos e categorias. O produto aparece no PDV na hora.",
    passos: ["Novo produto: nome, categoria, unidade e preço (o resto é recomendado).", "Aba Categorias: criar, renomear, cor e ordem no PDV.", "Importar planilha: cadastra muitos de uma vez."],
    ver: ["produto-cadastrar", "produto-importar", "produto-excluir"] },
  { id: "produto-cadastrar", cat: "produtos", titulo: "Cadastrar ou mudar o preço de um produto", niveis: AG, rota: "produtos",
    termos: "cadastrar produto novo produto mudar preco alterar preco preco errado custo margem codigo de barras ean unidade",
    resumo: "Em Produtos › Novo produto (ou clique num produto para editar).",
    passos: ["Nome: como aparece no botão, no cupom e na nota.", "Categoria e Unidade (UN, KG, L…). Em KG o PDV pede o peso.",
      "Preço de venda e Preço de custo (o custo ativa margem e lucro).", "Código de barras (não pode repetir) e código interno (atalho e balança).",
      "Controlar estoque, Favorito no PDV, Ativo para venda e Estoque mínimo.", "Dados fiscais (NCM, CEST, CFOP, CSOSN): confirme com o contador.", "Clique em Salvar."],
    dicas: ["Toda mudança de preço fica registrada (de quanto para quanto, quem e quando).", "Produtos da nota do fornecedor podem ser cadastrados direto na entrada do XML."] },
  { id: "produto-importar", cat: "produtos", titulo: "Importar produtos de uma planilha (Excel)", niveis: AG, rota: "produtos",
    termos: "importar planilha excel csv cadastrar muitos produtos de uma vez lista de produtos importar",
    resumo: "Monte a planilha, salve como CSV com ponto e vírgula e importe.",
    passos: ["Primeira linha com os títulos: nome; preco; codigo_barras; unidade; categoria; estoque; custo (também codigo e ncm).",
      "Salve como CSV separado por ponto e vírgula.", "Em Produtos, clique em Importar planilha, escolha o arquivo, confira e clique em Importar."],
    dicas: ["Só nome e preco são obrigatórios.", "Categorias novas são criadas; produtos com o mesmo código de barras são atualizados."] },
  { id: "produto-excluir", cat: "produtos", titulo: "Excluir ou desativar um produto", niveis: AG, rota: "produtos",
    termos: "excluir produto apagar produto deletar produto desativar produto tirar do pdv esconder produto",
    resumo: "Prefira desmarcar “Ativo para venda”: o produto some do PDV e o histórico continua certo.",
    passos: ["Abra o produto e desmarque Ativo para venda (ou esconda a categoria em Mostrar no PDV).", "Excluir de vez: só administrador, e só para cadastros feitos por engano."],
    atencao: ["Produto com vendas pode não ser excluído (“Este registro está em uso”). Desative em vez de excluir."] },
  { id: "tela-etiquetas", cat: "produtos", titulo: "Códigos de barras, QR Code e etiquetas", niveis: AG, rota: "etiquetas",
    termos: "etiqueta codigo de barras gerar codigo qr code imprimir etiqueta preco gondola ean pimaco qr wifi qr whatsapp",
    resumo: "Gere códigos para produtos sem código, etiquetas de preço e QR Codes do PIX, WhatsApp, Wi-Fi e cardápio.",
    passos: ["Escolha um produto (nome e preço entram sozinhos) ou escreva um título.", "Escolha o tipo: EAN-13, EAN-8, Code 128, ITF-14 ou QR.",
      "Gerar interno cria um código válido começando com 2 e pode gravar no cadastro.", "Escolha o tamanho e imprima, adicione à fila ou baixe PNG/SVG."] },
  { id: "tela-estoque", cat: "produtos", titulo: "Estoque: entrada, saída e contagem (inventário)", niveis: AG, rota: "estoque",
    termos: "estoque entrada saida contagem inventario acertar estoque estoque errado estoque negativo saldo historico do produto",
    resumo: "As vendas dão baixa e as notas dão entrada sozinhas. Aqui você registra o resto e as contagens.",
    passos: ["Encontre o produto (aba Todos e busca).", "Entrada: chegou sem XML. Saída: consumo/ajuste. Contagem: informe quanto existe de fato.", "Informe quantidade e motivo e clique em Registrar."],
    dicas: ["Estoque negativo? Provavelmente faltou uma entrada: corrija com uma Contagem.", "Perdas registre em Validade e perdas, para entrarem no lucro."] },
  { id: "tela-compras", cat: "produtos", titulo: "Compras: nota do fornecedor pelo XML", niveis: AG, rota: "compras",
    termos: "compras nota fiscal do fornecedor xml entrada de nota lancar nota fornecedor boleto custo novo preco sugerido",
    resumo: "Leia o XML da nota: estoque, custo, preço, lotes e contas a pagar são atualizados de uma vez.",
    passos: ["Em Compras › Entrada de nota (XML), escolha ou arraste o arquivo.", "Confira cada item (reconhece pelo código de barras ou pelo que aprendeu na primeira nota).",
      "Em Unid. por, informe quantas unidades vêm em cada caixa/fardo.", "Veja o novo custo e a margem; Usar R$ … sugere o preço novo.",
      "Deixe Lançar parcela(s) em contas a pagar marcado e clique em Dar entrada na nota."],
    atencao: ["O sistema não deixa lançar a mesma nota duas vezes (chave de acesso)."], ver: ["sugestao-compra"] },
  { id: "sugestao-compra", cat: "produtos", titulo: "Sugestão de compra, curva ABC e produtos parados", niveis: AG, rota: "compras",
    termos: "sugestao de compra quanto comprar pedido fornecedor whatsapp curva abc produtos parados dinheiro parado",
    resumo: "Quanto comprar de cada produto, quais mais faturam e o que está parado na prateleira.",
    passos: ["Sugestão: escolha os dias de vendas e de cobertura; ajuste e envie o pedido no WhatsApp do fornecedor.",
      "Curva ABC: A são os poucos que fazem 80% do faturamento (nunca deixe faltar).", "Parados: produtos sem venda há 15 a 180 dias; Criar promoção ajuda a girar."] },
  { id: "tela-validade", cat: "produtos", titulo: "Validade e perdas", niveis: AGC, rota: "validade",
    termos: "validade vencido vencendo lote perda quebra sobra do dia pao que sobrou estragado furto consumo interno",
    resumo: "Venda antes de vencer, retire o que venceu e saiba quanto a loja perde.",
    passos: ["Lotes entram pela nota (XML) ou à mão em Lotes e validades.", "Vencidos: retire e clique em Baixar como perda.", "Vencem em até 3 dias: Promoção para vender antes.",
      "Perdas: escolha produto, quantidade e motivo (vencido, avariado, quebra, sobra do dia, consumo, furto)."],
    dicas: ["A venda desconta primeiro do lote que vence antes.", "As perdas entram no lucro real."] },
  { id: "tela-promocoes", cat: "produtos", titulo: "Criar uma promoção", niveis: AG, rota: "promocoes",
    termos: "promocao criar promocao leve 3 pague 2 combo atacado happy hour preco por horario desconto programado",
    resumo: "Leve X pague Y, preço por dia/horário, atacado e combo. O caixa aplica sozinho, até sem internet.",
    passos: ["Em Promoções, clique em Nova promoção.", "Dê um nome (aparece no cupom) e escolha o tipo.", "Escolha os produtos (ou a categoria) e a regra.",
      "Em Quando vale, marque dias, horário e período (sem nada = sempre).", "Confira o exemplo e clique em Salvar."],
    dicas: ["Use Desligar para pausar sem apagar."], atencao: ["Promoções não se somam e itens com desconto manual não recebem promoção."] },

  // ================================================================ CLIENTES E FIADO
  { id: "tela-clientes", cat: "clientes", titulo: "Cadastrar um cliente", niveis: AGCT, rota: "clientes",
    termos: "cliente cadastrar cliente novo cliente endereco cep telefone whatsapp cnpj empresa",
    resumo: "Para CPF na nota, NF-e e fiado.",
    passos: ["Em Clientes, clique em Novo cliente.", "Nome e CPF ou CNPJ (o sistema confere).", "Digite o CEP: o endereço preenche sozinho; complete o número.", "Telefone com WhatsApp (para cobrar o fiado) e Salvar."],
    atencao: ["Para NF-e: endereço completo e CPF/CNPJ são obrigatórios."] },
  { id: "venda-fiado", cat: "clientes", titulo: "Vender no fiado (crediário)", niveis: AGC, rota: "pdv",
    termos: "fiado crediario pendura caderneta vender fiado anotar na conta cliente paga depois conta do cliente",
    resumo: "A venda vira dívida do cliente, com prazo e limite.",
    passos: ["Identifique o cliente no botão CPF.", "No pagamento, escolha Crediário e lance o valor.", "O sistema confere limite e bloqueio e mostra quanto ele já devia.", "Conclua a venda."],
    atencao: ["Acima do limite ou cliente bloqueado: só gerente ou administrador libera."], ver: ["tela-fiado", "erro-fiado"] },
  { id: "tela-fiado", cat: "clientes", titulo: "Fiado: receber, cobrar e extrato", niveis: AGC, rota: "fiado",
    termos: "fiado receber fiado cliente pagou fiado cobrar cliente cobranca whatsapp extrato limite prazo divida antiga caderno",
    resumo: "Quem deve, quanto venceu, receber, cobrar e ajustar.",
    passos: ["Receber: clique em Receber na linha do cliente, informe valor e forma e confirme (sai o recibo).",
      "Cobrar: monta a mensagem com o saldo e o PIX copia e cola, pronta para o WhatsApp.",
      "Extrato: compras, pagamentos e ajustes linha a linha.",
      "Limite (gerente): valor máximo, prazo e bloqueio. Ajuste manual: lançar a dívida antiga do caderno."],
    dicas: ["Dinheiro recebido entra no seu caixa aberto e aparece no fechamento."] },

  // ================================================================ GESTÃO
  { id: "tela-painel", cat: "gestao", titulo: "Painel: o resumo do dia", niveis: AG, rota: "painel",
    termos: "painel resumo do dia quanto vendi hoje faturamento hoje dashboard inicio",
    resumo: "Faturamento, ticket médio, lucro estimado, vendas por hora, formas de pagamento, quem está com caixa aberto e estoque baixo.",
    passos: ["Abra o Painel (primeira tela do administrador e do gerente).", "Clique em Ver todos no estoque baixo para ir ao estoque.", "Abrir o PDV leva direto à venda."] },
  { id: "tela-relatorios", cat: "gestao", titulo: "Relatórios: faturamento, mais vendidos e por operador", niveis: AG, rota: "relatorios",
    termos: "relatorio faturamento mes vendas do mes ticket medio mais vendidos por operador exportar excel contador csv",
    resumo: "Números do período para decidir: faturamento, ticket médio, lucro estimado, cancelamentos, por hora/dia, formas, operador e mais vendidos.",
    passos: ["Escolha Hoje, Ontem, 7 dias, 30 dias, Este mês, Mês passado ou Personalizado.", "Exportar CSV baixa os números para o Excel ou o contador."] },
  { id: "tela-financeiro", cat: "gestao", titulo: "Financeiro: lucro real, contas a pagar e fluxo de caixa", niveis: AG, rota: "financeiro",
    termos: "financeiro lucro lucro real quanto sobrou despesa conta a pagar boleto aluguel fluxo de caixa taxa maquininha",
    resumo: "Quanto sobrou de verdade, o que entra e sai e o que vence.",
    passos: ["Lucro real: faturamento − custo das mercadorias − taxas − perdas − despesas.", "Fluxo de caixa: entradas e saídas dia a dia e próximos pagamentos.",
      "Contas a pagar: Nova conta (pode repetir todo mês) e Pagar no dia.", "Taxas: o percentual da maquininha/banco por forma de pagamento."],
    dicas: ["Boletos de fornecedor não contam como despesa: o custo já entra quando o produto é vendido."], ver: ["conferencia-pix"] },
  { id: "conferencia-pix", cat: "gestao", titulo: "Conferir PIX e cartão com o extrato do banco", niveis: AG, rota: "financeiro",
    termos: "conferir pix conferencia extrato banco ofx pix falso comprovante falso maquininha bateu cartao conferir",
    resumo: "Descubra PIX lançado no caixa que não caiu no banco.",
    passos: ["Em Financeiro › Conferência, digite os totais da maquininha/banco por forma.", "Ou importe o extrato do PIX do dia em OFX ou CSV.", "Veja os PIX não encontrados no banco e clique em Salvar conferência."],
    atencao: ["PIX não encontrado pode ser comprovante falso ou erro do operador: confira com quem atendeu."] },
  { id: "tela-alertas", cat: "gestao", titulo: "Alertas antifraude e resumo do dia por e-mail", niveis: AG, rota: "alertas",
    termos: "alerta antifraude roubo desvio funcionario cancelando muito desconto demais gaveta resumo por email relatorio diario",
    resumo: "O sistema compara cada pessoa com a média da loja e avisa o que foge do normal. E manda o resumo do dia por e-mail.",
    passos: ["Veja os alertas da semana e os indicadores por operador.", "Resumo do dia: marque Enviar, informe até 5 e-mails, o horário e o fuso, e Salve. Use Enviar um teste agora."],
    atencao: ["Um alerta não é prova: converse, confira câmeras e o registro de atividades."] },
  { id: "registro-atividades", cat: "gestao", titulo: "Registro de atividades (quem fez o quê)", niveis: AG, rota: "configuracoes",
    termos: "registro de atividades auditoria quem cancelou quem mudou preco historico de acoes log",
    resumo: "Em Configurações › Registro de atividades: caixa, sangrias, cancelamentos, preços, usuários, notas, perdas, fiado, gaveta e mais.",
    passos: ["Abra Configurações › Registro de atividades e filtre pelo período ou ação."], dicas: ["Ninguém consegue apagar ou editar esse registro."] },

  // ================================================================ CONFIGURAÇÕES
  { id: "tela-configuracoes", cat: "config", titulo: "Configurações: o que tem em cada aba", niveis: T, rota: "configuracoes",
    termos: "configuracoes ajustes preferencias opcoes",
    resumo: "Loja, PIX, Delivery e cardápio, Restaurante, Impressora, Balança, Nota fiscal e Registro de atividades (cada nível vê as suas).",
    passos: ["Loja: dados do cupom, regime tributário, desconto máximo e mensagem.", "PIX: a chave da loja.", "Impressora e Balança: valem só para este computador.",
      "Restaurante e Delivery: regras do salão e do cardápio.", "Nota fiscal: só o administrador."],
    ver: ["config-loja", "config-pix", "config-impressora", "config-balanca", "config-nota-fiscal"] },
  { id: "config-loja", cat: "config", titulo: "Dados da loja, desconto máximo e mensagem do cupom", niveis: AG, rota: "configuracoes",
    termos: "dados da loja cnpj endereco nome da loja cabecalho cupom mensagem do cupom desconto maximo regime tributario simples",
    resumo: "O que sai no cabeçalho do cupom e as regras gerais.",
    passos: ["Configurações › Loja: razão social, fantasia, CNPJ, IE, telefone e endereço (o CEP preenche).", "Regime tributário (Simples, MEI ou normal).", "Desconto máximo para caixa e atendente (%).", "Mensagem no rodapé do cupom."] },
  { id: "config-pix", cat: "config", titulo: "Cadastrar a chave PIX da loja", niveis: AG, rota: "configuracoes",
    termos: "chave pix cadastrar pix configurar pix mercado pago confirmacao automatica",
    resumo: "Com a chave, o PDV, o fiado e o cardápio geram o PIX com o valor exato.",
    passos: ["Configurações › PIX: tipo de chave, a chave, o nome do recebedor e a cidade.", "Confira a prévia do QR de teste.", "Opcional: token de produção do Mercado Pago para confirmação automática."],
    ver: ["erro-pix-banco"] },
  { id: "config-impressora", cat: "config", titulo: "Configurar a impressora térmica", niveis: AGC, rota: "configuracoes",
    termos: "impressora configurar impressora termica usb serial bluetooth papel 80mm 58mm parear impressora imprimir teste cupom",
    resumo: "Pelo navegador (qualquer impressora) ou direto na térmica por USB/serial (corta papel e abre gaveta).",
    passos: ["Ligue e conecte a impressora.", "Configurações › Impressora: escolha Direto na térmica via USB.", "Largura do papel: 80 mm (comum) ou 58 mm.",
      "Clique em Parear impressora e escolha o modelo.", "Imprimir teste, marque as opções e Salvar."],
    dicas: ["Vale só para este computador: configure em cada caixa.", "Computador da cozinha: marque Imprimir pedidos dos garçons e do delivery."],
    ver: ["erro-impressora", "erro-acentos"] },
  { id: "config-balanca", cat: "config", titulo: "Configurar a balança", niveis: AGC, rota: "configuracoes",
    termos: "balanca configurar balanca toledo filizola urano elgin serial usb parear balanca peso automatico simulador",
    resumo: "Para vender por quilo sem digitar (Chrome ou Edge).",
    passos: ["Marque Usar balança neste caixa.", "Escolha a marca/protocolo e a velocidade (na dúvida, o padrão).", "Clique em Parear balança e escolha a porta; teste com Ler peso agora.",
      "Etiquetas da balança: informe se trazem preço ou peso e quantos dígitos tem o código."],
    dicas: ["Modo Simulador serve para treinar sem balança."] },
  { id: "config-nota-fiscal", cat: "config", titulo: "Configurar a nota fiscal (NFC-e e NF-e)", niveis: A, rota: "configuracoes",
    termos: "nota fiscal configurar nfce nfe certificado digital a1 csc focus nfe token homologacao producao sefaz",
    resumo: "Pelo provedor Focus NFe, com o certificado A1 e o CSC da SEFAZ.",
    passos: ["Tenha o certificado A1 e o CSC da NFC-e (site da SEFAZ do estado).", "Crie a conta no Focus NFe, cadastre a empresa, envie o certificado e o CSC.",
      "Copie os tokens de homologação e produção.", "Configurações › Nota fiscal: marque Emitir, cole os tokens e Salve.", "Teste em Homologação; com tudo certo, mude para Produção."],
    atencao: ["Revise NCM, CFOP e CSOSN dos produtos com o contador antes da produção."], ver: ["nota-fiscal-tipos", "erro-nota-rejeitada"] },
  { id: "nota-fiscal-tipos", cat: "config", titulo: "Cupom, NFC-e, NF-e e DANFE: qual é qual", niveis: AGC,
    termos: "cupom fiscal nao fiscal nfce nfe danfe diferenca nota consumidor nota empresa homologacao sem valor fiscal",
    resumo: "O sistema imprime vários documentos. Saiba qual é qual.",
    passos: ["Cupom não fiscal: comprovante interno.", "DANFE NFC-e: nota do consumidor, com QR Code (modelo 65).", "NF-e (modelo 55): para empresas, com endereço do cliente, em A4.",
      "Venda em contingência: feita sem internet, número provisório OFF-….", "Pedido/cozinha, conta da mesa, recibo do fiado, fechamento de caixa e QR do PIX."],
    atencao: ["Notas em homologação saem “sem valor fiscal”: só para testes."] },

  // ================================================================ EQUIPE
  { id: "tela-usuarios", cat: "equipe", titulo: "Usuários: criar login, trocar senha e bloquear", niveis: AG, rota: "usuarios",
    termos: "usuario criar login funcionario novo funcionario cadastrar funcionario trocar senha de funcionario bloquear funcionario demitido saiu da loja",
    resumo: "Um login para cada pessoa: assim você sabe quem vendeu, deu desconto ou cancelou.",
    passos: ["Clique em Novo usuário: nome, e-mail (o login) e senha inicial (8+), e o nível.", "Clique no usuário para mudar nome, nível, definir nova senha ou desmarcar Acesso liberado (bloquear)."],
    dicas: ["Funcionário saiu: bloqueie no mesmo dia. O histórico dele continua correto.", "Gerente só cria e gerencia caixas, garçons e cozinha."],
    atencao: ["Ninguém muda o próprio nível, e a loja nunca fica sem um administrador ativo."], ver: ["aparelhos", "excluir-usuario"] },
  { id: "aparelhos", cat: "equipe", titulo: "Aparelhos liberados: “Este aparelho não está liberado”", niveis: T, rota: "usuarios",
    termos: "aparelho nao liberado computador novo trocar computador trocar aparelho desvincular aparelho limite de aparelhos este aparelho nao esta liberado",
    resumo: "Cada login só funciona nos aparelhos liberados para ele (caixa: 1, gerente e admin: 2, garçom: livre).",
    passos: ["Computador trocado? O administrador ou gerente vai em Usuários › Aparelhos e clica em Desvincular no antigo.", "Depois, entre no aparelho novo: ele é liberado sozinho.",
      "Na tela de bloqueio, o gerente também pode usar Usar este no lugar."],
    atencao: ["São até 3 trocas em 30 dias. Depois disso, só o suporte libera."] },
  { id: "excluir-usuario", cat: "equipe", titulo: "Excluir um usuário (só o superusuário)", niveis: AG, rota: "usuarios",
    termos: "excluir usuario apagar usuario deletar funcionario remover login",
    resumo: "A loja bloqueia o acesso; excluir de vez é só com o suporte (superusuário).",
    passos: ["Para o funcionário não entrar mais: Usuários › clique nele › desmarque Acesso liberado.", "Se precisar apagar de vez, peça ao suporte: o login é apagado e o nome continua no histórico das vendas."] },

  // ================================================================ DADOS
  { id: "tela-backup", cat: "dados", titulo: "Backup: cópia de segurança dos dados", niveis: T, rota: "backup",
    termos: "backup copia de seguranca salvar dados baixar dados exportar importar restaurar voltar dados perdi dados apaguei sem querer",
    resumo: "O sistema faz cópias automáticas (todo dia por padrão) e você pode fazer uma na hora, baixar o arquivo e restaurar.",
    passos: ["Menu Backup › Fazer backup agora.", "Exportar arquivo: baixa um .json com tudo da loja (guarde em local seguro).",
      "Restaurar: em Cópias guardadas, clique em Restaurar e digite RESTAURAR. Antes, o sistema guarda o estado atual (dá para desfazer).",
      "Importar arquivo: envia um .json baixado antes e depois restaura."],
    dicas: ["O administrador escolhe a agenda e quais níveis podem fazer backup e baixar o arquivo."],
    atencao: ["O arquivo tem dados sensíveis (chaves de pagamento e fiscais).", "Restaurar e importar: só o administrador."] },
  { id: "mudanca-setor", cat: "dados", titulo: "Mudança de setor da loja (ex.: Supermercado → Restaurante)", niveis: T,
    termos: "mudar setor mudar segmento virar restaurante trocar tipo de negocio aviso dados serao apagados apagar e mudar",
    resumo: "O suporte pode mudar o setor da loja. O administrador vê um aviso e só confirma depois de baixar o backup completo.",
    passos: ["Leia o que será apagado e o que continua.", "Clique em Baixar backup completo (obrigatório) e guarde o arquivo.", "Digite APAGAR e clique em Apagar e mudar.", "Os produtos viram os de exemplo do novo setor."],
    dicas: ["Pode clicar em Decidir depois: o aviso volta no próximo acesso.", "O sistema guarda mais uma cópia no servidor antes de apagar."] },
  { id: "tela-assinatura", cat: "dados", titulo: "Minha assinatura: plano, faturas e licenças", niveis: AG, rota: "conta",
    termos: "assinatura plano mensalidade fatura boleto pagar sistema licenca vencida pacote adicional contratar",
    resumo: "Plano, próximo pagamento, pendências da loja, uso do mês, pacotes adicionais e faturas.",
    passos: ["Próximo pagamento: valor, vencimento, link e código para copiar.", "Pendências: o que falta configurar, com atalho.", "Pacotes: peça delivery, app do garçom, nota fiscal, caixa adicional e outros."],
    atencao: ["Licença vencida pausa as vendas, mas nada é apagado. Fale com o suporte para renovar."] },

  // ================================================================ SEM INTERNET
  { id: "sem-internet", cat: "problemas", titulo: "A internet caiu: continuo vendendo?", niveis: T, rota: "pdv",
    termos: "sem internet internet caiu offline wifi caiu sem rede vender sem internet vendas pendentes aguardando envio fila",
    resumo: "Sim. O caixa continua vendendo e envia tudo sozinho quando a internet voltar.",
    passos: ["Continue vendendo normalmente: aparece o aviso “Sem internet · vendendo offline”.", "PIX com QR continua funcionando; cartão funciona na maquininha.",
      "Toque no aviso para ver a fila e enviar na hora quando voltar."],
    atencao: ["NÃO limpe os dados do navegador nem troque de usuário do Windows enquanto houver vendas aguardando envio.",
      "Abrir/fechar caixa e emitir NFC-e precisam de internet (a nota sai quando a venda for enviada)."],
    ver: ["queda-energia", "erro-venda-offline-recusada"] },
  { id: "queda-energia", cat: "problemas", titulo: "Acabou a energia (ou o navegador fechou) no meio da venda", niveis: AGC, rota: "pdv",
    termos: "acabou energia caiu a luz desligou computador fechou navegador sem querer venda sumiu perdi a venda bateria acabou",
    resumo: "Nada se perde: cada item e pagamento é gravado na hora.",
    passos: ["Religue e abra o PDV.", "A venda volta como estava, com o aviso “Venda em andamento recuperada” e o que já foi pago."] },

  // ================================================================ MENSAGENS DE ERRO (do dia a dia)
  { id: "erro-caixa-fechado", cat: "problemas", titulo: "“Abra o caixa antes de finalizar vendas”", niveis: AGC, rota: "caixa",
    termos: "abra o caixa antes de finalizar vendas caixa fechado nao deixa vender nao finaliza",
    resumo: "O seu caixa está fechado.", passos: ["Clique em Abrir caixa no aviso amarelo do PDV ou vá em Caixa › Abrir caixa."], ver: ["abrir-caixa"] },
  { id: "erro-desconto", cat: "problemas", titulo: "“Desconto acima do limite permitido”", niveis: AGCT, rota: "pdv",
    termos: "desconto acima do limite permitido nao deixa dar desconto limite de desconto",
    resumo: "O desconto manual passou do limite dos caixas e atendentes.", passos: ["Chame um gerente para aplicar.", "Ou o administrador revisa o limite em Configurações › Loja."] },
  { id: "erro-troco", cat: "problemas", titulo: "“Troco só é permitido em pagamentos em dinheiro”", niveis: AGC, rota: "pdv",
    termos: "troco so e permitido em dinheiro valor maior no cartao pix maior que o total",
    resumo: "Você lançou no cartão ou PIX um valor maior que o total.", passos: ["Clique no ✕ do pagamento e lance o valor exato."] },
  { id: "erro-fiado", cat: "problemas", titulo: "“Identifique o cliente” ou “Limite de fiado excedido”", niveis: AGC, rota: "fiado",
    termos: "para vender no fiado identifique o cliente limite de fiado excedido cliente bloqueado fiado",
    resumo: "Fiado precisa de cliente escolhido e dentro do limite.", passos: ["Escolha o cliente no botão CPF.", "Acima do limite ou bloqueado: só gerente ou administrador libera (Fiado › Limite)."] },
  { id: "erro-pix-banco", cat: "problemas", titulo: "O banco não aceita o PIX copia e cola / QR", niveis: AGC, rota: "configuracoes",
    termos: "banco nao aceita pix qr invalido codigo pix invalido pix nao funciona chave invalida",
    resumo: "Quase sempre a chave cadastrada não é exatamente a do banco.",
    passos: ["Em Configurações › PIX, confira se a chave é exatamente a cadastrada no app do banco (celular com DDD, e-mail certo).", "Nome e cidade saem sem acentos, como os bancos exigem."] },
  { id: "erro-codigo-barras", cat: "problemas", titulo: "“Código não cadastrado” ao passar no leitor", niveis: AGC, rota: "produtos",
    termos: "codigo nao cadastrado leitor nao acha produto codigo de barras nao encontrado produto nao aparece bipar",
    resumo: "O código de barras não está em nenhum produto.", passos: ["Um gerente cadastra o código no produto (Produtos) ou na entrada da nota pelo XML."] },
  { id: "erro-balanca", cat: "problemas", titulo: "A balança não lança o peso", niveis: AGC, rota: "configuracoes",
    termos: "balanca nao funciona balanca nao le peso nao lanca peso balanca desconectada",
    resumo: "Normalmente é o pareamento ou o protocolo.", passos: ["Use Chrome ou Edge.", "Configurações › Balança: Parear balança de novo, confira marca/protocolo e velocidade.", "Teste com Ler peso agora."] },
  { id: "erro-impressora", cat: "problemas", titulo: "A impressora não imprime", niveis: AGC, rota: "configuracoes",
    termos: "impressora nao imprime cupom nao sai papel nao sai impressora parou impressora desconectada nao imprime",
    resumo: "Confira o básico e pareie de novo.",
    passos: ["Confira papel, tampa e se a impressora está ligada (luz).", "Em USB/serial: Configurações › Impressora › Parear impressora de novo.", "Use Chrome ou Edge.",
      "No Windows, se a impressora não aparecer no pareamento, use o modo Pelo navegador."], ver: ["config-impressora"] },
  { id: "erro-acentos", cat: "problemas", titulo: "Saem símbolos estranhos no lugar dos acentos", niveis: AGC, rota: "configuracoes",
    termos: "acento errado simbolos estranhos ç ã cupom letras estranhas caracteres",
    resumo: "A impressora não entende acentos.", passos: ["Desmarque Imprimir acentos em Configurações › Impressora."] },
  { id: "erro-nota-rejeitada", cat: "problemas", titulo: "A NFC-e foi rejeitada ou ficou “processando”", niveis: AGC, rota: "vendas",
    termos: "nota rejeitada nfce rejeitada sefaz rejeicao nota processando nota nao sai erro na nota",
    resumo: "A mensagem da SEFAZ diz o motivo.", passos: ["Abra a venda em Vendas: a mensagem aparece abaixo da nota.", "Causas comuns: NCM inválido, endereço da loja incompleto, token errado.", "Em “processando”, clique em Atualizar."] },
  { id: "erro-venda-offline-recusada", cat: "problemas", titulo: "Venda feita sem internet com erro na fila", niveis: AGC, rota: "pdv",
    termos: "venda offline com erro fila de vendas venda recusada nao enviou venda pendente",
    resumo: "Toque no aviso para ver o motivo (por exemplo, preço que mudou muito).", passos: ["O gerente confere e clica em Enviar agora, ou descarta se já foi lançada à mão."] },
  { id: "erro-outro-aparelho", cat: "problemas", titulo: "“Esta venda foi continuada em outro aparelho”", niveis: AGC, rota: "pdv",
    termos: "venda continuada em outro aparelho cupom sumiu outro computador",
    resumo: "Alguém clicou em Continuar aqui em outro aparelho.", passos: ["Este aparelho começa um cupom novo; nada é perdido."] },
  { id: "erro-nota-duplicada", cat: "problemas", titulo: "“Esta nota já foi lançada”", niveis: AG, rota: "compras",
    termos: "esta nota ja foi lancada xml duplicado nota repetida",
    resumo: "A chave de acesso desta NF-e já entrou. Lançar de novo duplicaria o estoque.", passos: ["Confira em Compras se ela já está lançada."] },
  { id: "erro-email-resumo", cat: "problemas", titulo: "O resumo por e-mail não chega", niveis: AG, rota: "alertas",
    termos: "resumo nao chega email nao chega relatorio diario nao chegou",
    resumo: "Confira os e-mails e o horário.", passos: ["Alertas › Resumo do dia: confira e-mails e horário.", "Procure no spam e use Enviar um teste agora.", "Se a tela disser que o envio não está ligado, fale com o suporte."] },
  { id: "erro-sem-permissao", cat: "problemas", titulo: "“Você não tem permissão para esta ação”", niveis: T,
    termos: "voce nao tem permissao sem permissao nao autorizado acesso negado nao aparece no menu",
    resumo: "A função não faz parte do seu nível de acesso.", passos: ["Peça ao administrador ou gerente.", "Veja em Níveis de acesso quem pode fazer o quê."], ver: ["niveis-acesso"] },
  { id: "erro-email-confirmacao", cat: "problemas", titulo: "Não recebi o e-mail de confirmação ou de nova senha", niveis: T,
    termos: "nao recebi email confirmacao email nao chegou link nao chegou",
    resumo: "Procure no spam.", passos: ["Procure no spam/lixo eletrônico.", "Funcionário: o administrador pode definir uma senha nova em Usuários."] },
  { id: "erro-vendas-pausadas", cat: "problemas", titulo: "“Vendas pausadas”, teste terminou ou licença venceu", niveis: T, rota: "conta",
    termos: "vendas pausadas teste terminou licenca venceu sistema bloqueado nao deixa vender conta suspensa",
    resumo: "Seus dados estão guardados: só as vendas param.", passos: ["Administrador: veja em Minha assinatura o motivo e regularize.", "Ou fale com o suporte pelo WhatsApp ou Pedir ajuda."] },
  { id: "erro-acesso-desativado", cat: "problemas", titulo: "“Seu acesso foi desativado”", niveis: T,
    termos: "acesso desativado usuario bloqueado nao consigo entrar bloquearam",
    resumo: "O seu usuário foi bloqueado.", passos: ["Só o administrador libera, em Usuários (marcando Acesso liberado)."] },
  { id: "erro-cozinha-nao-chega", cat: "problemas", titulo: "O pedido não chegou na cozinha", niveis: ["admin", "gerente", "caixa", "atendente", "cozinha"], rota: "cozinha",
    termos: "cozinha nao recebe pedido nao chegou nao aparece pedido sumiu cozinha vazia pedido parado aguardando aprovacao nao toca som cozinha",
    resumo: "Quase sempre o pedido está esperando aprovação, a tela da cozinha está sem internet ou foi aberta com outro login.",
    passos: ["Veja na mesa (tela Mesas) se o item está como “Aguardando aprovação”. Se estiver, o caixa ou gerente aprova (ou use Aprovar com senha).",
      "Na tela da cozinha, recarregue a página (F5) e confira se aparece “sem internet” no topo.",
      "Confirme que a cozinha entrou com um login do nível Cozinha (ou gerente/caixa) da mesma loja.",
      "Se o som não toca, clique uma vez na tela da cozinha: o navegador só libera o som depois de um clique."],
    dicas: ["Se a loja não quer aprovar cada pedido, desligue a aprovação em Configurações › Restaurante.", "Deixe a tela da cozinha em tela cheia (F11) e sem economia de energia."],
    ver: ["tela-cozinha", "senha-aprovacao", "sem-internet"] },
  { id: "erro-tela-travada", cat: "problemas", titulo: "O sistema travou, ficou girando ou a tela ficou branca", niveis: T,
    termos: "travou tela branca nao abre ficou carregando girando lento demora congelou",
    resumo: "Na maioria das vezes é internet ou uma cópia antiga presa no navegador.",
    passos: ["Aperte Ctrl+Shift+D para abrir o Diagnóstico e clique em Testar tudo agora.", "Recarregue com Ctrl+F5.", "Se tiver vendas aguardando envio, não limpe os dados do navegador.", "Persistiu? Pedir ajuda (botão no menu) e informe o código ao suporte."],
    ver: ["tela-diagnostico"] },

  // ================================================================ AJUDA E DIAGNÓSTICO
  { id: "tela-ajuda", cat: "comecar", titulo: "Como usar esta Central de Ajuda", niveis: T, rota: "ajuda",
    termos: "ajuda duvida como usar ajuda buscar tutorial manual apostila",
    resumo: "Escreva do seu jeito, anexe um print do erro ou peça ajuda a uma pessoa.",
    passos: ["Digite a dúvida como falaria (ex.: “como tiro o pão que sobrou”). Erros de escrita não atrapalham.",
      "Anexar print: o sistema lê o texto da imagem e procura a solução.", "Não resolveu? Clique em Falar com o suporte: o print vai junto.",
      "Em qualquer tela, F1 (ou Ajuda desta tela, no menu) abre a ajuda daquela tela."],
    dicas: ["Baixe a apostila completa em PDF pelo botão Apostila."] },
  { id: "tela-diagnostico", cat: "problemas", titulo: "Diagnóstico: entender um erro e testar o sistema", niveis: T, rota: "diagnostico",
    termos: "diagnostico erro teste check up entender erro relatorio de erro ctrl shift d caixa preta",
    resumo: "Grava tudo o que dá errado no aparelho e explica o problema e a solução.",
    passos: ["Abra com Ctrl+Shift+D (em qualquer tela), pelo menu Diagnóstico ou pelo botão Entender nos avisos de erro.",
      "Testar tudo agora: semáforo de internet, servidor, relógio, impressora, balança e mais.", "Gerar relatório: um arquivo para mandar ao suporte pelo WhatsApp."] },
  { id: "pedir-ajuda", cat: "comecar", titulo: "Pedir ajuda a uma pessoa do suporte", niveis: T,
    termos: "falar com suporte atendente humano chamado codigo de 6 numeros ajuda humana whatsapp suporte",
    resumo: "Você recebe um código de 6 números e o suporte já vê os detalhes do seu aparelho.",
    passos: ["Clique em Pedir ajuda (menu lateral) ou em Falar com o suporte aqui na Ajuda.", "Conte o que está acontecendo e, se quiser, anexe um print.", "Informe o código ao suporte. Ele pode entrar na sua loja para ajudar."] },

  // ================================================================ SUPERUSUÁRIO / SUPORTE
  { id: "tela-plataforma", cat: "plataforma", titulo: "Plataforma (superusuário)", niveis: [], rota: "plataforma", soSuper: true,
    termos: "plataforma faturamento de todas as lojas clientes leads cobrancas pedidos de pacotes",
    resumo: "Faturamento de todos os clientes, lojas, contatos, cobranças, pedidos de pacotes, licenças e dados/backup.",
    passos: ["Lojas › Gerenciar: plano, módulos, teste, bloquear, setor da loja, licenças, backups e usuários.", "Licenças: renovar ou expirar por ferramenta.", "Dados e backup: backup, exportar, importar e excluir lojas."] },
  { id: "super-licencas", cat: "plataforma", titulo: "Renovar ou expirar licenças", niveis: [], rota: "plataforma", soSuper: true,
    termos: "licenca renovar licenca expirar licenca vencimento pdv delivery garcom fiscal",
    resumo: "Plataforma › Licenças: por loja e por ferramenta (PDV, Delivery, Garçom, Nota fiscal).",
    passos: ["Marque as lojas e clique em Alterar licenças (ou Alterar numa linha).", "Escolha as ferramentas e: Renovar (+dias), Vencer em uma data, Sem prazo ou Expirar agora."],
    atencao: ["PDV vencido pausa as vendas na hora."] },
  { id: "super-excluir", cat: "plataforma", titulo: "Excluir lojas e usuários", niveis: [], rota: "plataforma", soSuper: true,
    termos: "excluir loja apagar cliente excluir todos excluir usuario administrador apagar login",
    resumo: "Plataforma › Dados e backup: lixeira na loja (ou várias/todas); botão Usuários para excluir pessoas.",
    passos: ["Digite EXCLUIR para confirmar. Antes, o sistema guarda uma cópia (Cópias guardadas › Recriar loja desfaz).", "Usuário com vendas: o login é apagado e o nome fica no histórico."] },
  { id: "super-setor", cat: "plataforma", titulo: "Mudar o setor de uma loja", niveis: [], rota: "plataforma", soSuper: true,
    termos: "mudar setor segmento restaurante supermercado trocar tipo de loja",
    resumo: "Lojas › Gerenciar › Setor da loja: escolha o setor e o que apagar; o cliente confirma depois de baixar o backup.",
    passos: ["Escolha o novo setor e Só o catálogo ou Tudo.", "Clique em Pedir mudança de setor.", "Enquanto o cliente não confirmar, dá para cancelar."] },
  { id: "tela-central-suporte", cat: "plataforma", titulo: "Central de suporte: chamados e entrar nas lojas", niveis: [], rota: "suporte", soEquipe: true,
    termos: "central de suporte chamado atender codigo entrar na loja modo suporte avisos equipe",
    resumo: "Chamados com código, entrar em qualquer loja (leitura ou total), avisos e equipe.",
    passos: ["Chamados: atenda pelo código; os anexos (prints) aparecem no chamado.", "Lojas › Entrar: motivo, tempo e modo.", "Ajuda: o que os clientes procuram e não acham."] },
];

/** Termos do dia a dia (viram artigos “O que é…?”). */
export const GLOSSARIO = [
  ["PDV", "Ponto de venda: a tela e o local onde a venda é registrada."], ["Cupom", "O comprovante impresso da venda."],
  ["Comanda", "Pedido aberto, identificado por mesa, número ou nome, pago no final."], ["Fundo de troco", "Dinheiro colocado na gaveta ao abrir o caixa."],
  ["Sangria", "Retirada de dinheiro da gaveta durante o turno."], ["Suprimento", "Reforço de dinheiro na gaveta, sem ser venda."],
  ["Ticket médio", "Valor médio gasto por venda."], ["Margem", "Quanto do preço de venda é lucro bruto, em porcentagem."],
  ["CMV", "Custo das mercadorias vendidas."], ["Lucro líquido", "O que sobra depois do custo, das taxas, das perdas e das despesas."],
  ["Fiado / crediário", "Venda para o cliente pagar depois, com limite e prazo."], ["Curva ABC", "Classificação dos produtos pelo faturamento: A (80%), B (15%), C (5%)."],
  ["PEPS", "Primeiro que vence, primeiro que sai: a venda consome o lote mais antigo."], ["Lote", "Parte do estoque com a mesma validade."],
  ["Contingência", "Venda feita sem internet, enviada depois."], ["XML da NF-e", "Arquivo oficial da nota do fornecedor, usado na entrada automática."],
  ["OFX", "Formato de extrato bancário usado na conferência do PIX."], ["Estoque mínimo", "Quantidade que dispara o alerta de reposição."],
  ["Inventário", "Contagem física dos produtos para acertar o estoque."], ["EAN", "O código de barras padrão das embalagens."],
  ["NFC-e", "Nota Fiscal de Consumidor Eletrônica (modelo 65)."], ["NF-e", "Nota Fiscal Eletrônica (modelo 55), com destinatário identificado."],
  ["DANFE", "Documento impresso que representa a nota eletrônica."], ["SEFAZ", "Secretaria da Fazenda do estado, que autoriza as notas."],
  ["Homologação", "Ambiente de testes da nota fiscal, sem valor fiscal."], ["Produção", "Ambiente real, em que as notas têm valor fiscal."],
  ["CSC", "Código de segurança do contribuinte, usado no QR Code da NFC-e."], ["NCM", "Código de 8 dígitos que classifica a mercadoria para impostos."],
  ["CFOP", "Código da natureza da operação. Venda dentro do estado: 5102."], ["CSOSN", "Situação tributária no Simples Nacional. Comum: 102."],
  ["ESC/POS", "Linguagem de comandos das impressoras térmicas."], ["PIX copia e cola", "O código do QR em texto, para colar no app do banco."],
  ["Backup", "Cópia de segurança de todos os dados da loja, para voltar se algo der errado."], ["Licença", "Permissão de uso de cada ferramenta (PDV, delivery, garçom, nota), com prazo."],
  ["Taxa de serviço", "Os 10% (ou o percentual da loja) cobrados na conta do restaurante."], ["Couvert", "Valor cobrado por pessoa (música ao vivo, por exemplo)."],
  ["NSU", "Número da transação do cartão, impresso no comprovante da maquininha."],
];

/** Grupos de palavras que querem dizer a mesma coisa (como o leigo fala). */
export const SINONIMOS = [
  ["apagar", "excluir", "deletar", "remover", "tirar", "eliminar", "sumir"],
  ["cancelar", "estornar", "desfazer", "anular", "devolver", "voltar"],
  ["entrar", "login", "logar", "acessar", "acesso", "senha"],
  ["imprimir", "impressora", "impressao", "imprime", "papel", "cupom", "termica"],
  ["pix", "qr", "qrcode", "copia", "chave"],
  ["fiado", "crediario", "pendura", "caderneta", "pendurar", "fiar"],
  ["garcom", "garconete", "atendente", "garcons"],
  ["sangria", "retirada", "retirar"],
  ["suprimento", "reforco"],
  ["balanca", "peso", "pesar", "quilo", "kg", "gramas", "granel"],
  ["internet", "offline", "rede", "wifi", "conexao", "online"],
  ["nota", "nfce", "nfe", "fiscal", "sefaz", "danfe"],
  ["produto", "item", "mercadoria", "artigo"],
  ["preco", "valor", "custo", "quanto"],
  ["desconto", "abatimento", "promocao", "oferta"],
  ["cliente", "freguês", "fregues", "consumidor", "comprador"],
  ["funcionario", "usuario", "operador", "colaborador", "empregado", "login"],
  ["caixa", "gaveta", "turno"],
  ["erro", "problema", "defeito", "bug", "falha", "travou", "travado", "nao funciona"],
  ["relatorio", "faturamento", "vendas", "resultado", "quanto vendi"],
  ["cardapio", "delivery", "entrega", "ifood", "pedido online"],
  ["mesa", "comanda", "salao"],
  ["cozinha", "chapa", "preparo", "kds"],
  ["mudar", "alterar", "trocar", "editar", "modificar", "corrigir", "atualizar", "mexer"],
  ["funcionario", "funcionaria", "empregado", "equipe", "colaborador"],
  ["estoque", "inventario", "contagem", "saldo"],
  ["vencido", "validade", "vencendo", "estragado", "perda"],
  ["backup", "copia", "seguranca", "restaurar", "exportar"],
  ["etiqueta", "codigo", "barras", "ean"],
  ["lucro", "ganho", "sobrou", "margem"],
  ["conta", "assinatura", "plano", "mensalidade", "fatura", "licenca"],
];
